# Generated by Django 6.0 on 2025-12-19 15:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(20)]
                    ),
                ),
                ("breed", models.CharField(max_length=100)),
                ("salary", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Cats",
                "ordering": ["name"],
            },
        ),
    ]
