# Generated by Django 6.0 on 2025-12-19 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="salary",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100000),
                    django.core.validators.MinValueValidator(1000),
                ]
            ),
        ),
    ]
